//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stonebot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Embedded {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Embedded() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stonebot.Resources.Embedded", typeof(Embedded).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Type hints
        ///if not Stonebot:
        ///    from stonebot import Stonebot
        ///.
        /// </summary>
        internal static string ScriptsTemplatePy {
            get {
                return ResourceManager.GetString("ScriptsTemplatePy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from typing import List, Optional, Any
        ///
        ///
        ///class ChatResponse:
        ///    data: List[&quot;ChatResponse.DataPoint&quot;]
        ///    drop_reason: &quot;ChatResponse.DropReason&quot;
        ///
        ///    class DataPoint:
        ///        message_id: str
        ///        is_sent: bool
        ///
        ///    class DropReason:
        ///        code: str
        ///        message: str
        ///
        ///
        ///class ChatterPermission:
        ///    level: int
        ///    role: str
        ///
        ///
        ///class MessageData:
        ///    broadcaster_id: str
        ///    broadcaster_user_name: str
        ///    broadcaster_login: str
        ///    chatter_id: str
        ///    chatter_user_name: str
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScriptsTypeHintsPyi {
            get {
                return ResourceManager.GetString("ScriptsTypeHintsPyi", resourceCulture);
            }
        }
    }
}
