//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stonebot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Embedded {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Embedded() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stonebot.Resources.Embedded", typeof(Embedded).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;title&gt;Authorization Failed&lt;/title&gt;
        ///    &lt;link href=&quot;https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;600&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            font-family: &apos;JetBrains Mono&apos;, monospace;
        ///            background-color: #242436;
        ///            display: flex;
        ///            align-items: center;
        ///            justify-content: center;
        ///            height: 100vh;
        ///            margin: 0;
        ///        }
        ///
        ///        .c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AuthFailHtml {
            get {
                return ResourceManager.GetString("AuthFailHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;title&gt;Authorization Succeeded&lt;/title&gt;
        ///    &lt;link href=&quot;https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;600&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            font-family: &apos;JetBrains Mono&apos;, monospace;
        ///            background-color: #242436;
        ///            display: flex;
        ///            align-items: center;
        ///            justify-content: center;
        ///            height: 100vh;
        ///            margin: 0;
        ///        } [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AuthSuccessHtml {
            get {
                return ResourceManager.GetString("AuthSuccessHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from typing import List, Optional, Any
        ///
        ///
        ///class ChatResponse:
        ///    data: List[&quot;ChatResponse.DataPoint&quot;]
        ///    drop_reason: &quot;ChatResponse.DropReason&quot;
        ///
        ///    class DataPoint:
        ///        message_id: str
        ///        is_sent: bool
        ///
        ///    class DropReason:
        ///        code: str
        ///        message: str
        ///
        ///
        ///class ChatterPermission:
        ///    level: int
        ///    role: str
        ///
        ///
        ///class MessageData:
        ///    broadcaster_id: str
        ///    broadcaster_user_name: str
        ///    broadcaster_login: str
        ///    chatter_id: str
        ///    chatter_user_name: str
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScriptsTypeHintsFile {
            get {
                return ResourceManager.GetString("ScriptsTypeHintsFile", resourceCulture);
            }
        }
    }
}
