<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFrameworks>net9.0;net9.0-windows</TargetFrameworks>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TwitchLib" Version="3.5.3" />
    <PackageReference Include="TwitchLib.Api.Core.Enums" Version="3.10.2" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
    <PackageReference Include="Microsoft.AspNetCore.DataProtection" Version="10.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.Extensions" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net9.0-windows'">
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.1" />
  </ItemGroup>

</Project>
