<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFrameworks>net10.0;net10.0-windows</TargetFrameworks>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TwitchLib.Api" Version="3.10.2" />
    <PackageReference Include="TwitchLib.Client" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
    <PackageReference Include="Microsoft.AspNetCore.DataProtection" Version="10.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.Extensions" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0-windows'">
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.1" />
  </ItemGroup>

</Project>
