<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TwitchLib.Api" Version="3.10.2" />
    <PackageReference Include="TwitchLib.Client" Version="4.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection" Version="10.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.Extensions" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StonebotSharedConstants\StonebotSharedConstants.csproj" />
  </ItemGroup>

</Project>
